
def list_devices() -> list[tuple[str,str]]: ...


class FPDevice:
    def __init__(self) -> None: ...
    def list_devices(self) -> list[tuple[str,str]]: ...
    def open(self, serial: str, firmware_file: str) -> int: ...
    def close(self) -> int: ...
    def set_wire_in(self, address: int, value: int, send_now: bool) -> int: ...
    def get_wire_out(self, address: int, refresh_wires: bool) -> int: ...
    def write_register(self, address: int, value: int) -> int: ...
    def read_register(self, address: int) -> int: ...
    def write_pipe(self, address: int, data: list[int], block_size: int) -> int: ...
    def read_pipe(self, address: int, data: list[int], block_size: int) -> int: ...
    def set_timeout(self, timeout: float) -> int: ...
    def set_device_id(self, deviceID: str) -> int: ...
    def get_device_id(self) -> str: ...
    def log(self, log_level: int, text: str, notime: bool) -> int: ...

